[changelog]
body = """
## 🎨 XTC-ThemePro {% if version %} ({{ version }}){% endif %}

{% for group, commits in commits | group_by(attribute="group") %}
{% if commits | length > 0 %}
### {{ group }}
{% for commit in commits | unique(attribute="message") %}
- {% if commit.scope %}{{ commit.scope }}: {% endif %}{{ commit.message | upper_first }}
  {% if commit.remote.username %}by @{{ commit.remote.username }}{% endif %}
  {% if commit.remote.pr_number %} in [#{{ commit.remote.pr_number }}]({{ remote_url() }}/pull/{{ commit.remote.pr_number }}){% endif %}
{% endfor %}
{% endif %}
{% endfor %}

{% if github and github.contributors | selectattr("is_first_time") | list | length > 0 %}
## 🎉 新贡献者
{% for contributor in github.contributors | selectattr("is_first_time") %}
- @{{ contributor.username }}{% if contributor.pr_number %} 在 [#{{ contributor.pr_number }}]({{ remote_url() }}/pull/{{ contributor.pr_number }}){% endif %} 第一次贡献
{% endfor %}
{% endif %}

{% if version and previous.version %}
**完整变更日志**: {{ remote_url() }}/compare/{{ previous.version }}...{{ version }}
{% endif %}

{% macro remote_url() -%}
https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro %}
"""
footer = "<!-- generated by git-cliff -->"
output = "CHANGELOG.md"
trim = true

[git]
commit_parsers = [
  {group = "◀️ 回滚的功能", message = "^revert"},
  {group = "✨  新增功能与优化", message = "^feat|^perf"},
  {group = "🐛 Bug 修复", message = "^fix"},
  {message = "^chore|^ci", skip = true},
  {message = "^doc|^style|^test|^refactor", skip = true}
]
conventional_commits = true
filter_commits = true
filter_unconventional = true
limit_commits = 50
link_parsers = []
protect_breaking_commits = false
sort_commits = "oldest"
split_commits = false
topo_order = false
