[changelog]
header = """
# 📋 更新日志

该项目遵循 [语义化版本](https://semver.org/lang/zh-CN/)。

"""
body = """
{% if version %}\
    ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
    ## [未发布]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits %}
    - {% if commit.scope %}**{{ commit.scope }}**: {% endif %}{{ commit.message | upper_first }}{% if commit.links %} ([{{ commit.id | truncate(length=7, end="") }}]({{ commit.links[0] }})){% endif %}
    {%- endfor %}
{% endfor %}

"""
trim = true
footer = """
---
💝 **谢谢喵!**
"""

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
commit_preprocessors = [
    { pattern = '\(#\d+\)', replace = ""},
    { pattern = '^feat', replace = "✨ 新功能"},
    { pattern = '^fix', replace = "🐛 修复"},
    { pattern = '^docs', replace = "📚 文档"},
    { pattern = '^perf', replace = "⚡ 性能"},
    { pattern = '^refactor', replace = "♻️ 重构"},
    { pattern = '^style', replace = "💄 样式"},
    { pattern = '^test', replace = "✅ 测试"},
    { pattern = '^chore', replace = "🔧 杂项"},
    { pattern = '^build', replace = "📦 构建"},
    { pattern = '^ci', replace = "👷 CI"},
]
commit_parsers = [
    { message = "^✨", group = "✨ 新功能"},
    { message = "^🐛", group = "🐛 Bug 修复"},
    { message = "^📚", group = "📚 文档"},
    { message = "^⚡", group = "⚡ 性能优化"},
    { message = "^♻️", group = "♻️ 重构"},
    { message = "^💄", group = "💄 样式"},
    { message = "^✅", group = "✅ 测试"},
    { message = "^🔧", group = "🔧 杂项"},
    { message = "^📦", group = "📦 构建"},
    { message = "^👷", group = "👷 CI/CD"},
    { message = "^feat", group = "✨ 新功能"},
    { message = "^fix", group = "🐛 Bug 修复"},
    { message = "^docs", group = "📚 文档"},
    { message = "^perf", group = "⚡ 性能优化"},
    { message = "^refactor", group = "♻️ 重构"},
    { message = "^style", group = "💄 样式"},
    { message = "^test", group = "✅ 测试"},
    { message = "^chore", group = "🔧 杂项"},
    { message = "^build", group = "📦 构建"},
    { message = "^ci", group = "👷 CI/CD"},
    { message = ".*", group = "其他", default_scope = "其他"},
]
protect_breaking_commits = false
filter_commits = false
tag_pattern = "v[0-9]*"
skip_tags = "v0.1.0-beta.1"
ignore_tags = ""
date_order = false
topo_order = false
sort_commits = "oldest"
